sudo: false
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21

jdk:
  - openjdk6
  - oraclejdk7

env:
    global:
    - JAVA6_HOME=/usr/lib/jvm/java-6-openjdk-amd64
    - PROJECT_DIR=AndroidTextExtensions

script:
  - jdk_switcher use openjdk6
  - # do stuff with Java 6
  - cd $PROJECT_DIR && ./gradlew :common:clean :generator:clean :common:build :generator:build :generator:test --stacktrace    
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7 
  - ./gradlew :library:clean :library:build :library:test :sample:clean :sample:assembleDebug --stacktrace 
