package digitaslbi.ext.fonts;

import digitaslbi.ext.common.Font;
import digitaslbi.ext.common.FontFamily;

/**
 * Generated by Android Text Extensions plugin.
 * @see <a href="https://github.com/DigitasLbiMobile/AndroidTextExtensions">Android Text Extensions</a>
 */
public class Chewy extends FontFamily {
  static {
    digitaslbi.ext.font.FontManager.registerFontFamily(new Chewy());
  }

  public static final Font Chewy = new Font("Chewy", "fonts/Chewy/Chewy.ttf");

  public Chewy() {
    super("Chewy", Chewy);
  }
}
