package digitaslbi.ext.fonts;

import digitaslbi.ext.common.Font;
import digitaslbi.ext.common.FontFamily;

/**
 * Generated by Android Text Extensions plugin.
 * @see <a href="https://github.com/DigitasLbiMobile/AndroidTextExtensions">Android Text Extensions</a>
 */
public class ComingSoon extends FontFamily {
  static {
    digitaslbi.ext.font.FontManager.registerFontFamily(new ComingSoon());
  }

  public static final Font ComingSoon = new Font("ComingSoon", "fonts/Coming_Soon/ComingSoon.ttf");

  public ComingSoon() {
    super("ComingSoon", ComingSoon);
  }
}
