package digitaslbi.ext.fonts;

import digitaslbi.ext.common.Font;
import digitaslbi.ext.common.FontFamily;

/**
 * Generated by Android Text Extensions plugin.
 * @see <a href="https://github.com/DigitasLbiMobile/AndroidTextExtensions">Android Text Extensions</a>
 */
public class PermanentMarker extends FontFamily {
  static {
    digitaslbi.ext.font.FontManager.registerFontFamily(new PermanentMarker());
  }

  public static final Font PermanentMarker = new Font("PermanentMarker", "fonts/Permanent_Marker/PermanentMarker.ttf");

  public PermanentMarker() {
    super("PermanentMarker", PermanentMarker);
  }
}
