/*
 * Copyright (c) 2015 DigitasLBi.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

package digitaslbi.ext.fonts;

import digitaslbi.ext.common.Font;
import digitaslbi.ext.common.FontFamily;

/**
 * Generated by Android Text Extensions plugin.
 * @see <a href="https://github.com/DigitasLbiMobile/AndroidTextExtensions">Android Text Extensions</a>
 */
public class NotoSerif extends FontFamily {
  public static final Font NotoSerif_Bold = new Font("NotoSerif.Bold", "fonts/Noto_Serif/NotoSerif-Bold.ttf");

  public static final Font NotoSerif_BoldItalic = new Font("NotoSerif.BoldItalic", "fonts/Noto_Serif/NotoSerif-BoldItalic.ttf");

  public static final Font NotoSerif_Italic = new Font("NotoSerif.Italic", "fonts/Noto_Serif/NotoSerif-Italic.ttf");

  public static final Font NotoSerif_Regular = new Font("NotoSerif.Regular", "fonts/Noto_Serif/NotoSerif-Regular.ttf");

  public NotoSerif() {
    super("NotoSerif", NotoSerif_Bold,NotoSerif_BoldItalic,NotoSerif_Italic,NotoSerif_Regular);
  }
}
