package digitaslbi.ext.fonts;

import digitaslbi.ext.common.Font;
import digitaslbi.ext.common.FontFamily;

/**
 * Generated by Android Text Extensions plugin.
 * @see <a href="https://github.com/DigitasLbiMobile/AndroidTextExtensions">Android Text Extensions</a>
 */
public class NotoSerif extends FontFamily {
  public static final Font NotoSerif_Bold = new Font("NotoSerif.Bold", "fonts/Noto_Serif/NotoSerif-Bold.ttf");

  public static final Font NotoSerif_BoldItalic = new Font("NotoSerif.BoldItalic", "fonts/Noto_Serif/NotoSerif-BoldItalic.ttf");

  public static final Font NotoSerif_Italic = new Font("NotoSerif.Italic", "fonts/Noto_Serif/NotoSerif-Italic.ttf");

  public static final Font NotoSerif_Regular = new Font("NotoSerif.Regular", "fonts/Noto_Serif/NotoSerif-Regular.ttf");

  public NotoSerif() {
    super("NotoSerif", NotoSerif_Bold,NotoSerif_BoldItalic,NotoSerif_Italic,NotoSerif_Regular);
  }
}
